# Generated by Django 5.2.1 on 2025-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_transactions_amount_alter_transactions_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='tr_type',
            field=models.CharField(choices=[('plus', 'Поступление'), ('minus', 'Отступление')], max_length=5),
        ),
    ]
