# Generated by Django 5.2.1 on 2025-06-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_transactions_tr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='bill_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
